name: check hugo build

# remember: cron sytnax
# cron: 'A B C D E'
#   A: minute (0 - 59)
#   B: hour (0 - 23)
#   C: day of the month (1 - 31)
#   D: month (1 - 12 or JAN-DEC)
#   E: day of the week (0 - 6 or SUN-SAT)
on:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'
          extended: true

      - name: Build
        run: hugo --minify